run_name: "aa005"

# OpenEphys sessions to be concatenated (the folders containing the Record Node folder)
session_paths:
  - "R:\\Basic_Sciences\\Phys\\SenzaiLab\\Ayo\\AA005\\Day3\\OpenField\\AA005_ADn_2026-02-10_10-58-07_OpenField"
  - "R:\\Basic_Sciences\\Phys\\SenzaiLab\\Ayo\\AA005\\Day3\\Homecage\\AA005_ADn_2026-02-10_12-51-33_Homecage"
# output path
local_output: "E:\\pipeline_output"

# central storage path
remote_output: "R:/Basic_Sciences/Phys/SenzaiLab/pipeline_output/"

per_shank: False
## --------------------- Default parameters --------------------- ##

# copying option
transfer_mode : "newer"  # options: "newer", "prompt", "skip", "overwrite"

# EEG downsampling frequency (Hz)
target_fs: 1250
verbose: True
overwrite: False

# SpikeInterface parallel processing arguments for concatenation
job_kwargs:
  n_jobs: 4
  chunk_duration: '2s'
  progress_bar: True
  mp_context: 'spawn'               # for Windows; use 'fork' for macOS/Linux